require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'config/environments/*'
    - 'gemfiles/vendor/bundle/**/*'
    - 'vendor/**/*'

  NewCops: disable
  SuggestExtensions:
    rubocop-capybara: false

Metrics/BlockLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10