require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'config/environments/*'
    - 'gemfiles/vendor/bundle/**/*'
    - 'vendor/**/*'

  NewCops: disable
  SuggestExtensions:
    rubocop-capybara: false

Metrics/BlockLength:
  IgnoredMethods:
    - 'context'
    - 'describe'
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false